image_dir: 'dataset/All_line_segments'
text_dir: 'dataset/All_line_texts'
model_dir: 'model/test'
base_dir: 'dataset/test'
train_batch_size: 4
eval_batch_size: 4
fp16: False
gradient_accumulation_steps: 1
num_train_epochs: 1
max_grad_norm: 1.0
logging_dir: './logs'
logging_steps: 10
evaluation_strategy: "steps"
eval_steps: 200
save_steps: 100000
warmup_steps: 500
weight_decay: 0.01
save_total_limit: 1
load_best_model_at_end: True
learning_rate: 5e-6
early_stopping_patience: 3
early_stopping_threshold: 0.0
wandb_project: "trocr-ocr-finetuning"
wandb_key: "cd2121ac29916b58f19853bee99f7fbdc3187ca4"
use_wandb: True
model_name: "microsoft/trocr-large-handwritten"
